# Generated by Django 5.1.6 on 2025-02-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(default=12, editable=False),
            preserve_default=False,
        ),
    ]
